import {
  TodaProfile,
  DriverApplicant,
  TodaDriverMember,
  DriverExemptionRequest,
  TodaAnnouncement,
  TodaBooking,
  TodaIncident,
  TodaAuditLog,
  NotificationItem,
} from '../types/toda';

// 1. Current Scoped TODA Profile (Calapan Central TODA)
export const CURRENT_TODA_PROFILE: TodaProfile = {
  id: 'toda-1',
  name: 'Calapan Central TODA',
  acronym: 'CCTODA',
  registrationNumber: 'TODA-CAL-2024-001',
  dateEstablished: 'March 15, 1998',
  terminalLocation: 'JP Rizal St. Central Terminal, Barangay San Vicente, Calapan City',
  pendingTerminalLocation: null,
  barangay: 'San Vicente / Poblacion',
  serviceCoverageArea: 'JP Rizal St., San Vicente, Lumangbayan, Tawiran, Poblacion Commercial Core',
  contactNumber: '+63 917 888 1234',
  email: 'admin@calapancentral-toda.org',
  officers: {
    president: 'Danilo "Ka Danny" Morales',
    vicePresident: 'Rogelio "Roger" Ramos',
    secretary: 'Elena "Nena" Gonzaga',
    treasurer: 'Vicente "Enteng" Sotto',
  },
  accreditationStatus: 'Active',
  accreditationExpiry: 'December 31, 2026',
  permitNumber: 'CAL-TODA-2024-001',
  barangayClearanceFile: {
    name: '2026_Barangay_SanVicente_Clearance_CCTODA.pdf',
    date: 'Jan 15, 2026',
  },
  rosterFile: {
    name: 'CCTODA_Accredited_Drivers_Roster_Q2_2026.pdf',
    date: 'May 01, 2026',
    count: 24,
  },
  isOtpVerified: true,
  misteepComplaintsCount: 1, // Supervisory review threshold is 3+ in 60 days
};

export const CURRENT_TODA_ADMIN = {
  id: 'TODA-ADM-001',
  name: 'Danilo "Ka Danny" Morales',
  email: 'd.morales@calapancentral-toda.org',
  phone: '+63 917 888 1234',
  role: 'TODA President',
  todaId: 'toda-1',
  todaName: 'Calapan Central TODA',
};

// 2. Driver Verification Stage Queue (TODA Level Screening)
export const MOCK_DRIVER_APPLICANTS: DriverApplicant[] = [
  {
    id: 'APP-DRV-001',
    name: 'Nestor "Boyet" Castro',
    phone: '+63 918 555 4101',
    licenseNo: 'N02-18-994821',
    vehiclePlate: '392-MV',
    chassisNo: 'CH-2024-8849',
    motorNo: 'MT-8841-KL',
    franchiseNo: 'CAL-2026-0412',
    submittedDate: 'May 10, 2026',
    daysPending: 2,
    isOverdue: false,
    onSubmittedRoster: true,
    tricyclePhotoUrl: '/assets/images/tricycle.png',
    photoVerified: true,
    rosterVerified: true,
    todaStageStatus: 'Submitted',
    notes: 'Complete papers submitted. Ready for final TODA board endorsement to LGU.',
  },
  {
    id: 'APP-DRV-002',
    name: 'Manuel "Manny" Diaz',
    phone: '+63 919 555 4102',
    licenseNo: 'N02-19-448210',
    vehiclePlate: '519-MV',
    chassisNo: 'CH-2023-7712',
    motorNo: 'MT-5521-XQ',
    franchiseNo: 'CAL-2026-0519',
    submittedDate: 'May 08, 2026',
    daysPending: 4,
    isOverdue: true, // Approaching SLA limit
    onSubmittedRoster: true,
    tricyclePhotoUrl: '/assets/images/tricycle.png',
    photoVerified: false,
    rosterVerified: true,
    todaStageStatus: 'TODA Review',
    notes: 'Tricycle sidecar photo shows unclear franchise stencil. Awaiting updated clear angle.',
  },
  {
    id: 'APP-DRV-003',
    name: 'Renato "Rene" Panganiban',
    phone: '+63 920 555 4103',
    licenseNo: 'N02-15-773821',
    vehiclePlate: '884-MV',
    chassisNo: 'CH-2022-9901',
    motorNo: 'MT-9921-TR',
    franchiseNo: 'CAL-2026-0884',
    submittedDate: 'May 11, 2026',
    daysPending: 1,
    isOverdue: false,
    onSubmittedRoster: false, // RULE 2.4: Mismatch Violation Warning
    tricyclePhotoUrl: '/assets/images/tricycle.png',
    photoVerified: true,
    rosterVerified: false,
    todaStageStatus: 'Submitted',
    notes: 'WARNING: Driver name does NOT appear in current CCTODA master roster submitted to LGU.',
  },
  {
    id: 'APP-DRV-004',
    name: 'Gilbert "Gibo" Teodoro',
    phone: '+63 921 555 4104',
    licenseNo: 'N02-20-119283',
    vehiclePlate: '741-MV',
    chassisNo: 'CH-2025-1102',
    motorNo: 'MT-1104-BB',
    franchiseNo: 'CAL-2026-0741',
    submittedDate: 'May 06, 2026',
    daysPending: 6,
    isOverdue: true, // SLA Exceeded (>5 Days)
    onSubmittedRoster: true,
    tricyclePhotoUrl: '/assets/images/tricycle.png',
    photoVerified: true,
    rosterVerified: true,
    todaStageStatus: 'TODA Review',
    notes: 'SLA overdue. Applicant followed up at terminal office.',
  },
  {
    id: 'APP-DRV-005',
    name: 'Arnel "Amang" Cruz',
    phone: '+63 922 555 4105',
    licenseNo: 'N02-14-883921',
    vehiclePlate: '603-MV',
    chassisNo: 'CH-2021-3329',
    motorNo: 'MT-3392-ZX',
    franchiseNo: 'CAL-2026-0603',
    submittedDate: 'May 09, 2026',
    daysPending: 3,
    isOverdue: false,
    onSubmittedRoster: true,
    tricyclePhotoUrl: '/assets/images/tricycle.png',
    photoVerified: true,
    rosterVerified: true,
    todaStageStatus: 'TODA Endorsed',
    notes: 'Endorsed by TODA President. Awaiting LGU Administrator final credential sign-off.',
  },
];

// 3. TODA Driver Membership Roster (All Affiliated with Calapan Central TODA)
export const MOCK_TODA_DRIVERS: TodaDriverMember[] = [
  {
    id: 'DRV-001',
    membershipNo: 'CCTODA-001',
    name: 'Aurelio "Auring" Bautista',
    phone: '+63 917 111 0201',
    email: 'aurelio.bautista@gmail.com',
    vehiclePlate: '773-MV',
    franchiseNo: 'CAL-2025-0773',
    licenseNo: 'N02-14-001928',
    terminalShift: 'Morning (6:00 AM – 2:00 PM)',
    serviceZone: 'JP Rizal – San Vicente Core',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Verified',
    accountStatus: 'Active',
    strikesCount: 0,
    rating: 4.9,
    totalTrips: 842,
    joinedDate: 'Jan 15, 2024',
  },
  {
    id: 'DRV-002',
    membershipNo: 'CCTODA-002',
    name: 'Vicente "Enteng" Sotto',
    phone: '+63 918 222 0202',
    email: 'enteng.sotto@yahoo.com',
    vehiclePlate: '482-MV',
    franchiseNo: 'CAL-2025-0482',
    licenseNo: 'N02-12-004829',
    terminalShift: 'Afternoon (2:00 PM – 10:00 PM)',
    serviceZone: 'San Vicente – Lumangbayan',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Verified',
    accountStatus: 'Active',
    strikesCount: 1, // Strike under review
    rating: 4.6,
    totalTrips: 620,
    joinedDate: 'Feb 01, 2024',
  },
  {
    id: 'DRV-003',
    membershipNo: 'CCTODA-003',
    name: 'Rogelio "Roger" Ramos',
    phone: '+63 919 333 0203',
    email: 'roger.ramos@gmail.com',
    vehiclePlate: '194-MV',
    franchiseNo: 'CAL-2025-0194',
    licenseNo: 'N02-16-009281',
    terminalShift: 'Morning (6:00 AM – 2:00 PM)',
    serviceZone: 'JP Rizal – City Hall Complex',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Verified',
    accountStatus: 'Active',
    strikesCount: 0,
    rating: 4.8,
    totalTrips: 915,
    joinedDate: 'Jan 10, 2024',
  },
  {
    id: 'DRV-004',
    membershipNo: 'CCTODA-004',
    name: 'Benjamin "Ben" Cruz',
    phone: '+63 920 444 0204',
    email: 'ben.cruz@gmail.com',
    vehiclePlate: '631-MV',
    franchiseNo: 'CAL-2025-0631',
    licenseNo: 'N02-17-003819',
    terminalShift: 'Night (10:00 PM – 6:00 AM)',
    serviceZone: 'Poblacion – Pier Port Terminal',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Verified',
    accountStatus: 'TODA Suspended',
    suspensionReason: 'Terminal Queue Violation: Cutting line at JP Rizal dispatch bay (3-day suspension).',
    suspendedAt: 'May 10, 2026',
    strikesCount: 2,
    rating: 4.2,
    totalTrips: 410,
    joinedDate: 'Mar 12, 2024',
  },
  {
    id: 'DRV-005',
    membershipNo: 'CCTODA-005',
    name: 'Danilo "Danny" Reyes',
    phone: '+63 921 555 0205',
    vehiclePlate: '809-MV',
    franchiseNo: 'CAL-2025-0809',
    licenseNo: 'N02-15-004128',
    terminalShift: 'Afternoon (2:00 PM – 10:00 PM)',
    serviceZone: 'San Vicente – Tawiran Route',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Verified',
    accountStatus: 'Active',
    strikesCount: 0,
    rating: 4.7,
    totalTrips: 780,
    joinedDate: 'Jan 20, 2024',
  },
  {
    id: 'DRV-006',
    membershipNo: 'CCTODA-006',
    name: 'Rodolfo "Rody" Aquino',
    phone: '+63 922 666 0206',
    vehiclePlate: '915-MV',
    franchiseNo: 'CAL-2024-0915',
    licenseNo: 'N02-11-008123',
    terminalShift: 'Morning (6:00 AM – 2:00 PM)',
    serviceZone: 'JP Rizal – Market Loop',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Suspended',
    accountStatus: 'LGU Deactivated',
    suspensionReason: 'LGU Policy Enforcement: Accumulated 5 safety and overcharging strikes.',
    suspendedAt: 'Apr 28, 2026',
    strikesCount: 5,
    rating: 3.8,
    totalTrips: 520,
    joinedDate: 'Jan 05, 2024',
  },
];

// 4. Driver Strike Exemption Requests
export const MOCK_EXEMPTION_REQUESTS: DriverExemptionRequest[] = [
  {
    id: 'EXM-2026-001',
    driverId: 'DRV-002',
    driverName: 'Vicente "Enteng" Sotto',
    strikeId: 'STRK-0091',
    incidentCategory: 'Overcharging Attempt / Detour',
    reason: 'Detour on JP Rizal was mandated by active DPWH culvert repair. Fare difference was due to extra 1.8km detour route.',
    evidenceFiles: ['DPWH_Road_Closure_Advisory_May09.pdf', 'GPS_Track_Log_BKG-8640.png'],
    submittedAt: 'May 10, 2026 • 09:00 AM',
    status: 'Approved',
    decisionNotes: 'TODA verified road closure notice with Barangay San Vicente captain. Strike cleared.',
  },
  {
    id: 'EXM-2026-002',
    driverId: 'DRV-004',
    driverName: 'Benjamin "Ben" Cruz',
    strikeId: 'STRK-0092',
    incidentCategory: 'Route Deviation / Drop-off Delay',
    reason: 'Passenger requested emergency stop at Calapan Doctor’s Hospital due to acute asthma distress of child companion.',
    evidenceFiles: ['Hospital_Triage_Admittance_Slip.pdf'],
    submittedAt: 'May 11, 2026 • 03:30 PM',
    status: 'Pending Review',
    decisionNotes: 'Awaiting hospital admittance verification from passenger family.',
  },
  {
    id: 'EXM-2026-003',
    driverId: 'DRV-006',
    driverName: 'Rodolfo "Rody" Aquino',
    strikeId: 'STRK-0093',
    incidentCategory: 'Repeated Reckless Driving (5th Strike)',
    reason: 'Claims passenger video evidence was manipulated and taken out of context during heavy rain.',
    evidenceFiles: ['Driver_Written_Affidavit.pdf'],
    submittedAt: 'May 08, 2026 • 01:15 PM',
    status: 'Escalated to LGU',
    decisionNotes: 'Exemption involves 5th strike and permanent deactivation threshold. Escalated to LGU Legal & Franchising Board.',
  },
];

// 5. TODA-Scoped Announcements (Broadcast to CCTODA Drivers Only)
export const MOCK_TODA_ANNOUNCEMENTS: TodaAnnouncement[] = [
  {
    id: 'TODA-ANN-001',
    title: 'Strict Adherence to Terminal Queue and Passenger Loading Bay',
    message: 'All drivers must load passengers strictly at the designated JP Rizal bays. Cutting the terminal line will result in immediate 3-day TODA terminal suspension.',
    category: 'Terminal Rules',
    urgency: 'High Priority',
    isPublished: true,
    sendPushNotification: true,
    createdBy: 'Danilo "Ka Danny" Morales (President)',
    createdAt: 'May 08, 2026 • 08:00 AM',
  },
  {
    id: 'TODA-ANN-002',
    title: 'Quarterly TODA General Assembly & Elections Notice',
    message: 'General meeting scheduled on Sunday, May 24, 2026 at 2:00 PM in San Vicente Barangay Gymnasium. Attendance of all unit franchise holders is mandatory.',
    category: 'Meeting Notice',
    urgency: 'Standard',
    isPublished: true,
    sendPushNotification: true,
    createdBy: 'Elena "Nena" Gonzaga (Secretary)',
    createdAt: 'May 10, 2026 • 10:30 AM',
  },
  {
    id: 'TODA-ANN-003',
    title: 'Q2 Barangay Clearance and Franchise Renewal Document Submission',
    message: 'Please submit photocopies of updated Barangay Clearance and 2026 MTOP sticker receipt to the TODA office before June 15, 2026.',
    category: 'Document Renewal',
    urgency: 'Standard',
    isPublished: true,
    sendPushNotification: false,
    createdBy: 'Danilo "Ka Danny" Morales (President)',
    createdAt: 'May 11, 2026 • 01:00 PM',
  },
  {
    id: 'TODA-ANN-004',
    title: 'Rainy Season Sidecar Canopy and Brake Inspection Advisory (Draft)',
    message: 'Free roadworthiness and brake inspection will be conducted at the terminal garage this coming Saturday.',
    category: 'Safety Advisory',
    urgency: 'Standard',
    isPublished: false,
    sendPushNotification: false,
    createdBy: 'Rogelio "Roger" Ramos (VP)',
    createdAt: 'May 12, 2026 • 09:30 AM',
  },
];

// 6. TODA Bookings Ledger (Scoped to Calapan Central TODA)
export const MOCK_TODA_BOOKINGS: TodaBooking[] = [
  {
    id: 'BKG-9011',
    bookingCode: 'BK-CAL-9011',
    passengerName: 'Maria Clara Santos',
    passengerPhone: '+63 917 555 1001',
    driverName: 'Aurelio "Auring" Bautista',
    vehiclePlate: '773-MV',
    pickupLocation: 'JP Rizal Central Terminal',
    dropoffLocation: 'Calapan City Public Market',
    distanceKm: 2.4,
    fareAmount: 18.0,
    tripMode: 'Single Commuter',
    status: 'Completed',
    paymentMethod: 'Cash',
    timestamp: 'May 12, 2026 • 09:15 AM',
  },
  {
    id: 'BKG-9012',
    bookingCode: 'BK-CAL-9012',
    passengerName: 'Joshua Dizon',
    passengerPhone: '+63 918 555 1002',
    driverName: 'Vicente "Enteng" Sotto',
    vehiclePlate: '482-MV',
    pickupLocation: 'San Vicente National High School',
    dropoffLocation: 'Calapan Port Ferry Terminal',
    distanceKm: 5.1,
    fareAmount: 60.0,
    tripMode: 'Solo Charter',
    status: 'Completed',
    paymentMethod: 'GCash / Digital',
    timestamp: 'May 12, 2026 • 09:40 AM',
  },
  {
    id: 'BKG-9013',
    bookingCode: 'BK-CAL-9013',
    passengerName: 'Elena Gonzaga',
    passengerPhone: '+63 919 555 1003',
    driverName: 'Rogelio "Roger" Ramos',
    vehiclePlate: '194-MV',
    pickupLocation: 'Provincial Capitol Complex',
    dropoffLocation: 'San Vicente Parish Church',
    distanceKm: 1.8,
    fareAmount: 15.0,
    tripMode: 'Single Commuter',
    status: 'Completed',
    paymentMethod: 'Cash',
    timestamp: 'May 12, 2026 • 10:05 AM',
  },
  {
    id: 'BKG-9014',
    bookingCode: 'BK-CAL-9014',
    passengerName: 'Carlos Mendoza',
    passengerPhone: '+63 920 555 1004',
    driverName: 'Danilo "Danny" Reyes',
    vehiclePlate: '809-MV',
    pickupLocation: 'JP Rizal Commercial Core',
    dropoffLocation: 'Lumangbayan Riverside',
    distanceKm: 3.6,
    fareAmount: 20.0,
    tripMode: 'Shared Ride',
    status: 'Completed',
    paymentMethod: 'Cash',
    timestamp: 'May 12, 2026 • 10:25 AM',
  },
  {
    id: 'BKG-9015',
    bookingCode: 'BK-CAL-9015',
    passengerName: 'Ana Patricia Non',
    passengerPhone: '+63 921 555 1005',
    driverName: 'Aurelio "Auring" Bautista',
    vehiclePlate: '773-MV',
    pickupLocation: 'San Vicente Barangay Hall',
    dropoffLocation: 'Calapan Doctors Hospital',
    distanceKm: 3.2,
    fareAmount: 19.0,
    tripMode: 'Single Commuter',
    status: 'In Progress',
    paymentMethod: 'GCash / Digital',
    timestamp: 'May 12, 2026 • 10:45 AM',
  },
];

// 7. TODA-Level Incident Queue (Review Before LGU Escalation)
export const MOCK_TODA_INCIDENTS: TodaIncident[] = [
  {
    id: 'TODA-INC-001',
    bookingId: 'BKG-8812',
    tripId: 'TRP-2026-00481',
    driverName: 'Vicente "Enteng" Sotto',
    vehiclePlate: '482-MV',
    reporterName: 'Joshua "Josh" Dizon',
    reporterRole: 'Passenger',
    category: 'Overcharging Dispute',
    description: 'Passenger claimed driver asked for ₱30 instead of ₱20 for San Vicente to Tawiran dropoff during heavy rain.',
    submittedAt: 'May 11, 2026 • 04:15 PM',
    status: 'Under Investigation',
    findings: 'TODA Officer Sotto contacted driver. Driver stated rain detour was required. Case under local mediation.',
  },
  {
    id: 'TODA-INC-002',
    bookingId: 'BKG-8750',
    tripId: 'TRP-2026-00420',
    driverName: 'Benjamin "Ben" Cruz',
    vehiclePlate: '631-MV',
    reporterName: 'Aurelio "Auring" Bautista',
    reporterRole: 'Driver',
    category: 'Terminal Queue Violation',
    description: 'Driver Cruz cut the passenger dispatch line at JP Rizal bay without waiting for his rotation number.',
    submittedAt: 'May 10, 2026 • 08:30 AM',
    status: 'Resolved (TODA Level)',
    findings: 'Driver Cruz apologized and accepted 3-day terminal loading suspension.',
  },
  {
    id: 'TODA-INC-003',
    bookingId: 'BKG-8902',
    tripId: 'TRP-2026-00501',
    driverName: 'Rodolfo "Rody" Aquino',
    vehiclePlate: '915-MV',
    reporterName: 'Elena "Nena" Gonzaga',
    reporterRole: 'Passenger',
    category: 'Reckless Driving & Threat',
    description: 'Driver was swerving through pedestrian lanes and verbally threatened commuter when asked to slow down.',
    submittedAt: 'May 09, 2026 • 06:10 PM',
    status: 'Escalated to LGU',
    findings: 'Severe safety breach involving harassment. Beyond TODA local jurisdiction. Escalated to LGU Administrator.',
    escalationReason: 'Verbal threat and gross safety misconduct requiring official LGU franchise review.',
    escalatedAt: 'May 09, 2026 • 08:00 PM',
  },
];

// 8. TODA Seed Audit Logs
export const MOCK_TODA_AUDIT_LOGS: TodaAuditLog[] = [
  {
    id: 'TLOG-001',
    log_id: 'TAUD-001',
    toda_admin_id: 'TODA-ADM-001',
    actor_name: 'Danilo "Ka Danny" Morales',
    action_type: 'DRIVER_ENDORSED_TO_LGU',
    target_id: 'APP-DRV-005',
    target_name: 'Arnel "Amang" Cruz',
    details: 'Verified roster match and tricycle roadworthiness photo. Endorsed driver application to LGU Administrator.',
    performed_at: 'May 09, 2026 • 02:30 PM',
    category: 'Driver Verification',
  },
  {
    id: 'TLOG-002',
    log_id: 'TAUD-002',
    toda_admin_id: 'TODA-ADM-001',
    actor_name: 'Danilo "Ka Danny" Morales',
    action_type: 'DRIVER_TODA_SUSPENDED',
    target_id: 'DRV-004',
    target_name: 'Benjamin "Ben" Cruz',
    details: 'Suspended driver member for 3 days due to terminal line cutting violation at JP Rizal dispatch bay.',
    performed_at: 'May 10, 2026 • 09:00 AM',
    category: 'Membership',
  },
  {
    id: 'TLOG-003',
    log_id: 'TAUD-003',
    toda_admin_id: 'TODA-ADM-001',
    actor_name: 'Danilo "Ka Danny" Morales',
    action_type: 'INCIDENT_ESCALATED_TO_LGU',
    target_id: 'TODA-INC-003',
    target_name: 'Incident #TODA-INC-003 (Rodolfo Aquino)',
    details: 'Escalated reckless driving and verbal threat incident to LGU Administrator for official franchise suspension.',
    performed_at: 'May 09, 2026 • 08:00 PM',
    category: 'Incident',
  },
  {
    id: 'TLOG-004',
    log_id: 'TAUD-004',
    toda_admin_id: 'TODA-ADM-001',
    actor_name: 'Danilo "Ka Danny" Morales',
    action_type: 'ANNOUNCEMENT_PUBLISHED',
    target_id: 'TODA-ANN-001',
    target_name: 'Strict Adherence to Terminal Queue',
    details: 'Broadcast terminal queue discipline notice to all 24 affiliated drivers.',
    performed_at: 'May 08, 2026 • 08:00 AM',
    category: 'Announcement',
  },
  {
    id: 'TLOG-005',
    log_id: 'TAUD-005',
    toda_admin_id: 'TODA-ADM-001',
    actor_name: 'Danilo "Ka Danny" Morales',
    action_type: 'EXEMPTION_REQUEST_APPROVED',
    target_id: 'EXM-2026-001',
    target_name: 'Vicente "Enteng" Sotto',
    details: 'Approved detour strike exemption following DPWH road closure verification on JP Rizal St.',
    performed_at: 'May 10, 2026 • 11:30 AM',
    category: 'Membership',
  },
];

// 9. TODA Notifications
export const MOCK_TODA_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-01',
    title: 'New Driver Affiliation Application',
    description: 'Nestor "Boyet" Castro submitted an application for Calapan Central TODA review.',
    time: '15 mins ago',
    unread: true,
  },
  {
    id: 'NOTIF-02',
    title: 'Overdue Verification Warning',
    description: 'Application for Gilbert "Gibo" Teodoro has exceeded 5-day combined review SLA.',
    time: '2 hours ago',
    unread: true,
  },
  {
    id: 'NOTIF-03',
    title: 'Strike Exemption Appeal Filed',
    description: 'Benjamin "Ben" Cruz submitted medical hospital proof for strike review.',
    time: 'Yesterday',
    unread: false,
  },
  {
    id: 'NOTIF-04',
    title: 'LGU Accreditation Status: Active',
    description: 'Calapan Central TODA municipal permit CAL-TODA-2024-001 valid until Dec 31, 2026.',
    time: '3 days ago',
    unread: false,
  },
];
