import {
  TodaProfile,
  DriverApplicant,
  TodaDriverMember,
  DriverExemptionRequest,
  TodaAnnouncement,
  TodaBooking,
  TodaIncident,
  TodaAuditLog,
  NotificationItem,
} from '../types/toda';

// 1. Current Scoped TODA Profile (Calapan Central TODA)
export const CURRENT_TODA_PROFILE: TodaProfile = {
  id: 'toda-1',
  name: 'Calapan Central TODA',
  acronym: 'CCTODA',
  registrationNumber: 'TODA-CAL-2024-001',
  dateEstablished: 'March 15, 1998',
  terminalLocation: 'JP Rizal St. Central Terminal, Barangay San Vicente, Calapan City',
  pendingTerminalLocation: null,
  barangay: 'San Vicente / Poblacion',
  serviceCoverageArea: 'JP Rizal St., San Vicente, Lumangbayan, Tawiran, Poblacion Commercial Core',
  contactNumber: '+63 917 888 1234',
  email: 'admin@calapancentral-toda.org',
  officers: {
    president: 'Danilo "Ka Danny" Morales',
    vicePresident: 'Rogelio "Roger" Ramos',
    secretary: 'Elena "Nena" Gonzaga',
    treasurer: 'Vicente "Enteng" Sotto',
  },
  accreditationStatus: 'Active',
  accreditationExpiry: 'December 31, 2026',
  accreditationNo: 'CAL-TODA-2024-001',
  permitNumber: 'CAL-TODA-2024-001',
  barangayClearanceFile: {
    name: '2026_Barangay_SanVicente_Clearance_CCTODA.pdf',
    date: 'Jan 15, 2026',
    url: '/assets/images/tricycle.png',
  },
  rosterFile: {
    name: 'CCTODA_Accredited_Drivers_Roster_Q2_2026.pdf',
    date: 'May 01, 2026',
    count: 24,
    url: '/assets/images/tricycle.png',
  },
  isOtpVerified: true,
  misteepComplaintsCount: 1, // Supervisory review threshold is 3+ in 60 days
};

export const CURRENT_TODA_ADMIN = {
  id: 'TODA-ADM-001',
  name: 'Danilo "Ka Danny" Morales',
  email: 'd.morales@calapancentral-toda.org',
  phone: '+63 917 888 1234',
  role: 'TODA President',
  todaId: 'toda-1',
  todaName: 'Calapan Central TODA',
};

// 2. Driver Verification Stage Queue (TODA Level Screening)
export const MOCK_DRIVER_APPLICANTS: DriverApplicant[] = [
  {
    id: 'APP-DRV-001',
    name: 'Nestor "Boyet" Castro',
    phone: '+63 918 555 4101',
    licenseNo: 'N02-18-994821',
    vehiclePlate: '392-MV',
    chassisNo: 'CH-2024-8849',
    motorNo: 'MT-8841-KL',
    franchiseNo: 'CAL-2026-0412',
    submittedDate: 'May 10, 2026',
    daysPending: 2,
    isOverdue: false,
    onSubmittedRoster: true,
    tricyclePhotoUrl: '/assets/images/tricycle.png',
    photoVerified: true,
    rosterVerified: true,
    todaStageStatus: 'Submitted',
    notes: 'Complete papers submitted. Ready for final TODA board endorsement to LGU.',
  },
  {
    id: 'APP-DRV-002',
    name: 'Eduardo "Eddie" Santos',
    phone: '+63 919 555 4102',
    licenseNo: 'N02-17-482910',
    vehiclePlate: '518-MV',
    chassisNo: 'CH-2023-1102',
    motorNo: 'MT-5512-AB',
    franchiseNo: 'CAL-2026-0918',
    submittedDate: 'May 08, 2026',
    daysPending: 4,
    isOverdue: true,
    onSubmittedRoster: false, // Roster mismatch flag
    tricyclePhotoUrl: '/assets/images/tricycle.png',
    photoVerified: false,
    rosterVerified: false,
    todaStageStatus: 'TODA Review',
    notes: 'Submitted membership info does not match the active TODA driver roster.',
  },
  {
    id: 'APP-DRV-003',
    name: 'Felipe "Ipe" Mendoza',
    phone: '+63 920 555 4103',
    licenseNo: 'N02-16-118492',
    vehiclePlate: '804-MV',
    chassisNo: 'CH-2025-9914',
    motorNo: 'MT-9923-ZX',
    franchiseNo: 'CAL-2026-0104',
    submittedDate: 'May 05, 2026',
    daysPending: 7,
    isOverdue: true,
    onSubmittedRoster: true,
    tricyclePhotoUrl: '/assets/images/tricycle.png',
    photoVerified: true,
    rosterVerified: true,
    todaStageStatus: 'TODA Endorsed',
    notes: 'Verified by TODA President. Forwarded to LGU Franchising Office.',
  },
  {
    id: 'APP-DRV-004',
    name: 'Gabriel "Gaby" Reyes',
    phone: '+63 921 555 4104',
    licenseNo: 'N02-19-338291',
    vehiclePlate: '109-MV',
    chassisNo: 'CH-2024-7712',
    motorNo: 'MT-4418-PL',
    franchiseNo: 'CAL-2026-0315',
    submittedDate: 'May 04, 2026',
    daysPending: 8,
    isOverdue: true,
    onSubmittedRoster: false,
    tricyclePhotoUrl: '/assets/images/tricycle.png',
    photoVerified: false,
    rosterVerified: false,
    todaStageStatus: 'Resubmission Required',
    rejectionReason: 'Submitted license photo is unreadable. Please resubmit a clear photo.',
    notes: 'Driver requested to update license scan.',
  },
];

// 3. Accredited TODA Driver Members Roster
export const MOCK_TODA_DRIVERS: TodaDriverMember[] = [
  {
    id: 'DRV-001',
    membershipNo: 'CCTODA-001',
    name: 'Aurelio "Auring" Bautista',
    phone: '+63 917 111 0201',
    email: 'auring.bautista@gmail.com',
    vehiclePlate: '773-MV',
    franchiseNo: 'CAL-2025-0773',
    licenseNo: 'N02-14-001829',
    serviceZone: 'JP Rizal St. – Central Terminal',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Verified',
    accountStatus: 'Active',
    strikesCount: 0,
    rating: 4.9,
    totalTrips: 1240,
    joinedDate: 'Jan 15, 2024',
  },
  {
    id: 'DRV-002',
    membershipNo: 'CCTODA-002',
    name: 'Vicente "Enteng" Sotto',
    phone: '+63 918 222 0202',
    email: 'enteng.sotto@gmail.com',
    vehiclePlate: '482-MV',
    franchiseNo: 'CAL-2025-0482',
    licenseNo: 'N02-12-004918',
    serviceZone: 'San Vicente – City Hall Corridor',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Verified',
    accountStatus: 'Active',
    strikesCount: 1,
    rating: 4.6,
    totalTrips: 890,
    joinedDate: 'Jan 15, 2024',
  },
  {
    id: 'DRV-003',
    membershipNo: 'CCTODA-003',
    name: 'Rogelio "Roger" Ramos',
    phone: '+63 919 333 0203',
    email: 'roger.ramos@gmail.com',
    vehiclePlate: '194-MV',
    franchiseNo: 'CAL-2025-0194',
    licenseNo: 'N02-16-009281',
    serviceZone: 'JP Rizal – City Hall Complex',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Verified',
    accountStatus: 'Active',
    strikesCount: 0,
    rating: 4.8,
    totalTrips: 915,
    joinedDate: 'Jan 10, 2024',
  },
  {
    id: 'DRV-004',
    membershipNo: 'CCTODA-004',
    name: 'Benjamin "Ben" Cruz',
    phone: '+63 920 444 0204',
    email: 'ben.cruz@gmail.com',
    vehiclePlate: '631-MV',
    franchiseNo: 'CAL-2025-0631',
    licenseNo: 'N02-17-003819',
    serviceZone: 'Poblacion – Pier Port Terminal',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Verified',
    accountStatus: 'Suspension Review',
    suspensionReason: 'Overcharging report on JP Rizal route. Endorsed to LGU for policy review.',
    suspendedAt: 'May 10, 2026',
    strikesCount: 2,
    rating: 4.2,
    totalTrips: 410,
    joinedDate: 'Mar 12, 2024',
  },
  {
    id: 'DRV-005',
    membershipNo: 'CCTODA-005',
    name: 'Danilo "Danny" Reyes',
    phone: '+63 921 555 0205',
    vehiclePlate: '809-MV',
    franchiseNo: 'CAL-2025-0809',
    licenseNo: 'N02-15-004128',
    serviceZone: 'San Vicente – Tawiran Route',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Verified',
    accountStatus: 'Active',
    strikesCount: 0,
    rating: 4.7,
    totalTrips: 780,
    joinedDate: 'Jan 20, 2024',
  },
  {
    id: 'DRV-006',
    membershipNo: 'CCTODA-006',
    name: 'Rodolfo "Rody" Aquino',
    phone: '+63 922 666 0206',
    vehiclePlate: '915-MV',
    franchiseNo: 'CAL-2024-0915',
    licenseNo: 'N02-11-008123',
    serviceZone: 'JP Rizal – Market Loop',
    todaVerificationStatus: 'Verified',
    lguVerificationStatus: 'Suspended',
    accountStatus: 'LGU Deactivated',
    suspensionReason: 'LGU Policy Enforcement: Accumulated 5 safety and overcharging strikes.',
    suspendedAt: 'Apr 28, 2026',
    strikesCount: 5,
    rating: 3.8,
    totalTrips: 520,
    joinedDate: 'Jan 05, 2024',
  },
];

// 4. Driver Strike Exemption Requests with Clickable Evidence Attachments
export const MOCK_EXEMPTION_REQUESTS: DriverExemptionRequest[] = [
  {
    id: 'EXM-2026-001',
    driverId: 'DRV-002',
    driverName: 'Vicente "Enteng" Sotto',
    strikeId: 'STRK-0091',
    incidentCategory: 'Overcharging Attempt / Detour',
    reason: 'Detour on JP Rizal was mandated by active DPWH culvert repair. Fare difference was due to extra 1.8km detour route.',
    evidenceFiles: [
      { id: 'ev-1', name: 'DPWH_Road_Closure_Advisory_May09.pdf', type: 'document', url: '/assets/images/tricycle.png' },
      { id: 'ev-2', name: 'GPS_Track_Log_BKG-8640.png', type: 'image', url: '/assets/images/tricycle.png' },
    ],
    submittedAt: 'May 10, 2026 • 09:00 AM',
    status: 'Approved',
    decisionNotes: 'TODA verified road closure notice with Barangay San Vicente captain. Endorsed to LGU.',
  },
  {
    id: 'EXM-2026-002',
    driverId: 'DRV-004',
    driverName: 'Benjamin "Ben" Cruz',
    strikeId: 'STRK-0092',
    incidentCategory: 'Route Deviation / Drop-off Delay',
    reason: 'Passenger requested emergency stop at Calapan Doctor’s Hospital due to acute distress of child companion.',
    evidenceFiles: [
      { id: 'ev-3', name: 'Hospital_Emergency_Triage_Slip.pdf', type: 'document', url: '/assets/images/tricycle.png' },
    ],
    submittedAt: 'May 11, 2026 • 03:30 PM',
    status: 'Pending Review',
    decisionNotes: 'Awaiting hospital admittance confirmation from passenger family.',
  },
  {
    id: 'EXM-2026-003',
    driverId: 'DRV-006',
    driverName: 'Rodolfo "Rody" Aquino',
    strikeId: 'STRK-0093',
    incidentCategory: 'Repeated Reckless Driving (5th Strike)',
    reason: 'Driver claims video clip was taken out of context during heavy rain and localized flooding.',
    evidenceFiles: [
      { id: 'ev-4', name: 'Driver_Written_Affidavit.pdf', type: 'document', url: '/assets/images/tricycle.png' },
      { id: 'ev-5', name: 'Dashcam_Rain_Playback.mp4', type: 'document', url: '/assets/images/tricycle.png' },
    ],
    submittedAt: 'May 08, 2026 • 01:15 PM',
    status: 'Escalated to LGU',
    decisionNotes: 'Exemption involves 5th strike deactivation threshold. Escalated for LGU Franchising Board review.',
  },
];

// 5. TODA-Scoped Announcements (Broadcast to CCTODA Drivers Only)
export const MOCK_TODA_ANNOUNCEMENTS: TodaAnnouncement[] = [
  {
    id: 'TODA-ANN-001',
    title: 'Strict Adherence to Terminal Loading Bays & Standard Fare',
    message: 'All drivers must load passengers strictly at designated JP Rizal bays. Fares must strictly follow City Ordinance No. 118 base rates.',
    category: 'Terminal Rules',
    urgency: 'High Priority',
    isPublished: true,
    sendPushNotification: true,
    createdBy: 'Danilo "Ka Danny" Morales (President)',
    createdAt: 'May 08, 2026 • 08:00 AM',
  },
  {
    id: 'TODA-ANN-002',
    title: 'Quarterly General Assembly and Roster Verification Meeting',
    message: 'All CCTODA drivers are requested to attend the Q2 assembly on May 20 at San Vicente Covered Court for roster updating.',
    category: 'Meeting Notice',
    urgency: 'Standard',
    isPublished: true,
    sendPushNotification: true,
    createdBy: 'Danilo "Ka Danny" Morales (President)',
    createdAt: 'May 10, 2026 • 02:00 PM',
  },
  {
    id: 'TODA-ANN-003',
    title: 'Draft Notice: Annual Barangay Clearance Upload Deadline',
    message: 'Reminder to all members to submit updated Barangay Clearances before June 30, 2026 for LGU accreditation renewal.',
    category: 'Document Renewal',
    urgency: 'Standard',
    isPublished: false,
    sendPushNotification: true,
    createdBy: 'Danilo "Ka Danny" Morales (President)',
    createdAt: 'May 12, 2026 • 10:00 AM',
  },
];

// 6. TODA Bookings Mock Data
export const MOCK_TODA_BOOKINGS: TodaBooking[] = [
  {
    id: 'BKG-8640',
    bookingCode: 'TRP-2026-08640',
    passengerName: 'Maria Clara Santos',
    passengerPhone: '+63 917 555 1029',
    driverName: 'Aurelio "Auring" Bautista',
    vehiclePlate: '773-MV',
    pickupLocation: 'Xentro Mall Calapan',
    dropoffLocation: 'Calapan City Hall',
    distanceKm: 2.8,
    fareAmount: 20,
    tripMode: 'Single Commuter',
    status: 'Completed',
    paymentMethod: 'Cash',
    timestamp: 'May 12, 2026 • 09:15 AM',
  },
  {
    id: 'BKG-8641',
    bookingCode: 'TRP-2026-08641',
    passengerName: 'Juan Dela Cruz',
    passengerPhone: '+63 918 555 2048',
    driverName: 'Vicente "Enteng" Sotto',
    vehiclePlate: '482-MV',
    pickupLocation: 'San Vicente Church',
    dropoffLocation: 'Oriental Mindoro Provincial Hospital',
    distanceKm: 3.5,
    fareAmount: 25,
    tripMode: 'Shared Ride',
    status: 'In Progress',
    paymentMethod: 'Cash',
    timestamp: 'May 12, 2026 • 09:40 AM',
  },
  {
    id: 'BKG-8642',
    bookingCode: 'TRP-2026-08642',
    passengerName: 'Elena Ramos',
    passengerPhone: '+63 919 555 3012',
    driverName: 'Rogelio "Roger" Ramos',
    vehiclePlate: '194-MV',
    pickupLocation: 'Calapan Public Market',
    dropoffLocation: 'Lumangbayan Barangay Hall',
    distanceKm: 4.2,
    fareAmount: 45,
    tripMode: 'Solo Charter',
    status: 'Completed',
    paymentMethod: 'Cash',
    timestamp: 'May 12, 2026 • 08:30 AM',
  },
];

// 7. TODA Incidents Mock Data
export const MOCK_TODA_INCIDENTS: TodaIncident[] = [
  {
    id: 'INC-2026-012',
    bookingId: 'BKG-8630',
    tripId: 'TRP-2026-08630',
    driverName: 'Vicente "Enteng" Sotto',
    vehiclePlate: '482-MV',
    reporterName: 'Carlos Mendoza',
    reporterRole: 'Passenger',
    category: 'Fare Discrepancy / Overcharging',
    description: 'Passenger reported a ₱5 fare discrepancy over the approved City Ordinance No. 118 rate on JP Rizal St route.',
    submittedAt: 'May 10, 2026 • 11:30 AM',
    status: 'Pending Review',
    findings: 'Under review by TODA Board. Driver states 1.8km detour was required due to road repair.',
  },
  {
    id: 'INC-2026-010',
    bookingId: 'BKG-8590',
    tripId: 'TRP-2026-08590',
    driverName: 'Rodolfo "Rody" Aquino',
    vehiclePlate: '915-MV',
    reporterName: 'LGU Transport Inspector',
    reporterRole: 'Commuter',
    category: 'Reckless Driving',
    description: 'Reported abrupt swerving near Calapan Public Market intersection.',
    submittedAt: 'Apr 28, 2026 • 02:15 PM',
    status: 'Escalated to LGU',
    findings: '5th safety strike. Escalated to LGU Franchising Board for formal review.',
  },
];

// 8. TODA Audit Logs
export const MOCK_TODA_AUDIT_LOGS: TodaAuditLog[] = [
  {
    id: 'LOG-TODA-012',
    log_id: 'AUD-TODA-012',
    toda_admin_id: 'TODA-ADM-001',
    actor_name: 'Danilo "Ka Danny" Morales',
    action_type: 'DRIVER_APPLICATION_ENDORSED',
    target_id: 'APP-DRV-003',
    target_name: 'Felipe "Ipe" Mendoza',
    details: 'Verified applicant master roster affiliation and tricycle photo. Endorsed application to LGU Franchising Board.',
    performed_at: 'May 12, 2026 • 09:10 AM',
    category: 'Driver Verification',
  },
  {
    id: 'LOG-TODA-011',
    log_id: 'AUD-TODA-011',
    toda_admin_id: 'TODA-ADM-001',
    actor_name: 'Danilo "Ka Danny" Morales',
    action_type: 'ANNOUNCEMENT_PUBLISHED',
    target_id: 'TODA-ANN-001',
    target_name: 'Strict Adherence to Terminal Loading Bays',
    details: 'Published high-priority announcement to CCTODA Driver App members.',
    performed_at: 'May 08, 2026 • 08:00 AM',
    category: 'Announcement',
  },
];

// 9. Toda Header Notifications Mock Data
export const MOCK_TODA_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-TODA-01',
    title: 'New Driver Application Received',
    description: 'Nestor "Boyet" Castro (392-MV) submitted a driver verification request.',
    time: '10 mins ago',
    unread: true,
  },
  {
    id: 'NOTIF-TODA-02',
    title: 'Strike Exemption Appeal Filed',
    description: 'Benjamin "Ben" Cruz submitted a strike exemption appeal for Incident #INC-2026-012.',
    time: '1 hour ago',
    unread: true,
  },
  {
    id: 'NOTIF-TODA-03',
    title: 'LGU Accreditation Active',
    description: 'Calapan Central TODA accreditation permit #CAL-TODA-2024-001 is in good standing.',
    time: 'Yesterday',
    unread: false,
  },
];
