/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

export type Language = 'tl' | 'en';

const translations = {
  tl: {
    start: "Magsimula na",
    hasAccount: "May account na?",
    loginLink: " Mag-login",
    selectRole: "Paano mo gustong gamitin ang SAKAY?",
    selectRoleDesc: "Pumili ng uri ng account para makapagsimula. Maaari kang magparehistro bilang pasahero o drayber.",
    passenger: "Pasahero",
    passengerDesc: "Mag-book ng tricycle sa paligid ng Calapan City",
    driver: "Drayber",
    driverDesc: "Tumanggap ng mga booking at pamahalaan ang iyong mga biyahe",
    continue: "Magpatuloy",
    skip: "Laktawan",
    back: "Bumalik",
    loginTitle: "Mag-login",
    loginSubtitle: "Ilagay ang iyong mobile number at password upang makapasok sa iyong account.",
    phoneOrEmail: "Mobile Number",
    password: "Password",
    forgotPassword: "Nakalimutan ang Password?",
    dontHaveAccount: "Wala pang account?",
    registerLink: "Gumawa ng Account",
    createAccountTitle: "Gumawa ng account",
    prepareYourDetails: "Ilagay ang iyong mga detalye.",
    registerTitle: "Gumawa ng account",
    registerSubtitle: "Ilagay ang iyong mga detalye.",
    fullName: "Buong Pangalan",
    fullNamePlaceholder: "Buong Pangalan",
    mobileNumber: "Mobile Number",
    mobileNumberPlaceholder: "Mobile Number",
    mobilePhone: "Mobile Number (+63)",
    passwordPlaceholder: "Password",
    confirmPassword: "Kumpirmahin ang Password",
    confirmPasswordPlaceholder: "Kumpirmahin ang Password",
    affiliatedToda: "Kinabibilangang TODA",
    licenseNumber: "Numero ng Lisensya",
    plateNumber: "Plaka ng Tricycle",
    franchiseNumberOptional: "Franchise / MTOP No. (Kung Meron)",
    verificationDocs: "Mga Dokumento para sa Beripikasyon",
    driversLicense: "Professional Driver's License",
    licenseUploaded: "Nai-upload: drivers_license_front.jpg",
    tapToUpload: "I-tap upang mag-upload ng litrato",
    orCrMtop: "Tricycle OR / CR & MTOP Permit",
    orCrUploaded: "Nai-upload: tricycle_or_cr_permit.pdf",
    photoWithTricycle: "Litrato kasama ang Tricycle & Body No.",
    photoUploaded: "Nai-upload: driver_with_unit_photo.jpg",
    alreadyHaveAccount: "May account na?",
    enterPhoneAndPassword: "Ilagay ang iyong mobile number at password.",
    sendOtpCode: "Ipadala ang OTP Code",
    forgotPasswordTitle: "Nakalimutan ang Password?",
    forgotPasswordDesc: "Ilagay ang iyong rehistradong mobile number upang makatanggap ng 6-digit verification code.",
    verifyOtpTitle: "Ilagay ang OTP",
    otpSentTo: "Nagpadala kami ng 6-digit code sa iyong mobile number:",
    resendCode: "I-send ulit ang Code",
    otpResentSuccess: "Bagong OTP ang ipinadala sa iyong mobile number.",
    confirmOtp: "Kumpirmahin",
    iAgree: "Sumasang-ayon ako",
    termsTitle: "Mga Tuntunin ng Serbisyo",
    privacyTitle: "Patakaran sa Privacy",
    lastUpdatedTerms: "Huling binago: Hulyo 2026",
    didNotReceiveCode: "Walang natanggap na code?",
    resend: "Ipadala Muli",
    newPasswordTitle: "Bagong Password",
    newPasswordDesc: "Gumawa ng bagong secure password para sa iyong driver account.",
    newPassword: "Bagong Password",
    saveAndLogin: "I-save at Mag-login",
    applicationStatusTitle: "Status ng Aplikasyon",
    submissionComplete: "1. Kumpleto ang Pagsumite",
    submissionCompleteDesc: "Driver license at tricycle photos ay natanggap na.",
    todaRosterVerification: "2. Beripikasyon sa TODA Driver Roster",
    todaRosterVerificationDesc: "Sinusuri ng TODA Board ang inyong unit allocation bago i-endorso sa LGU.",
    lguAccreditation: "3. Panghuling Akreditasyon at Pag-activate ng LGU",
    lguAccreditationDesc: "Panghuling pag-apruba at pag-activate ng driver dispatch account.",
    goToDashboard: "Pumunta sa Driver Dashboard",
    createAccountBtn: "Magpatuloy",
    backToLogin: "Bumalik sa Login",
    phoneRequired: "Kailangan ang mobile number",
    passwordRequired: "Kailangan ang password",
    nameRequired: "Kailangan ang buong pangalan",
    passwordsMustMatch: "Dapat magtugma ang password",
    successLogin: "Matagumpay na nakapag-login!",
    successRegister: "Matagumpay na nakapag-register!",
    onboarding1Title: "Mag-book ng Biyahe",
    onboarding1Desc: "Mabilis at madaling pag-book ng traysikel sa isang pindot lang kahit nasaan ka.",
    onboarding2Title: "Tamang Pamasahe",
    onboarding2Desc: "Malinaw at tapat na presyo para sa bawat biyahe, walang hulaan.",
    onboarding3Title: "Ligtas at Maaasahan",
    onboarding3Desc: "Siguradong drayber na lisensyado at rehistrado sa TODA ang susundo sa iyo.",
    // Prepare Documents Screen
    prepareDocsTitle: "Ihanda ang mga Dokumento",
    prepareDocsSubtitle: "Upang mapanatiling ligtas ang SAKAY para sa lahat, kailangan naming i-verify ang iyong pagkakakilanlan at mga dokumento ng sasakyan. Ihanda ang mga ito bago magpatuloy.",
    prepareDocsBullet1: "Ihanda ang orihinal na mga dokumento.",
    prepareDocsBullet2: "Siguraduhing malinaw at mababasa ang lahat ng detalye.",
    prepareDocsBullet3: "Iwasan ang malabong kuha, silaw, at anino.",
    prepareDocsBullet4: "Kumuha ng larawan sa maliwanag na lugar.",
    docDriversLicenseTitle: "Driver's License (LTO)",
    docDriversLicenseDesc: "Para ma-verify ang iyong pagkakakilanlan at lisensya sa pagmamaneho.",
    docMtopTitle: "Motorized Tricycle Operator's Permit (MTOP)",
    docMtopDesc: "Para ma-verify ang iyong prangkisa at awtorisadong ruta ng operasyon.",
    docCrTitle: "Certificate of Registration (CR)",
    docCrDesc: "Para ma-verify ang impormasyon ng iyong sasakyan.",
    docOrTitle: "Official Receipt (OR)",
    docOrDesc: "Para ma-verify ang pinakahuling rehistro ng iyong sasakyan.",
    estimatedTimeNotice: "Tinatayang humigit-kumulang 5 minuto",
    // Driver's License Guidelines Screen
    step1Of4: "Hakbang 1 ng 4",
    prepareLicenseTitle: "Ihanda ang iyong Driver's License",
    forClearPhoto: "Para sa malinaw na larawan:",
    licenseBullet1: "Gamitin lamang ang iyong opisyal na Driver's License card.",
    licenseBullet2: "Hindi tinatanggap ang papel na lisensya.",
    licenseBullet3: "Ilagay ang ID sa patag na ibabaw.",
    licenseBullet4: "Siguraduhing kita ang buong ID.",
    licenseBullet5: "Iwasan ang silaw at anino.",
    licenseBullet6: "Kumuha ng larawan sa maliwanag na lugar.",
    // License Scanner & Review 1-6 Screens
    scanFrontPromptPrefix: "I-scan ang ",
    scanBackPromptPrefix: "I-scan ang ",
    scanFrontWord: "harap",
    scanBackWord: "likod",
    scanPromptMid: " ng iyong ",
    philippineDriversLicense: "Philippine Driver's License",
    scanPromptSuffix: " sa frame",
    tipsTitle: "Para kumuha ng perpektong litrato:",
    scanTipsHeader: "Para kumuha ng perpektong litrato:",
    useUploadInstead: "Mag-upload na lang ng larawan",
    scanTip1: "Ilagay ang iyong ID sa isang lugar na malinaw at maliwanag.",
    scanTip2: "Siguraduhing kasya nang buo ang ID sa loob ng frame.",
    scanTip3: "I-tap ang capture area para mag-focus.",
    scanTip4: "Manatiling hindi gumagalaw at pindutin ang button ng camera.",
    reviewPhotoTitle: "Maayos na ba ang kuha?",
    reviewPhotoSubtitle: "Siguraduhing malinaw at mababasa ang lahat ng impormasyon sa iyong ID.",
    useThisPhoto: "Gamitin ang Larawang Ito",
    retakePhoto: "Kuhanan Muli",
    ocrProcessingNotice: "Sandali lang habang kinukuha namin ang impormasyon mula sa iyong dokumento.",
    confirmInfoTitle: "Kumpirmahin ang iyong impormasyon",
    confirmInfoSubtitle: "Pakisuri kung tama ang lahat ng detalye.",
    useRearCameraError: "Gamitin ang likurang camera upang kuhanan ang iyong lisensya.",
    labelFullName: "BUONG PANGALAN",
    labelDob: "PETSA NG KAPANGANAKAN",
    labelGender: "KASARIAN",
    genderMale: "Male",
    genderFemale: "Female",
    labelAddress: "TIRAHAN",
    labelLicenseNumber: "NUMERO NG DRIVER LICENSE",
    labelDlCodes: "RESTRICTIONS",
    labelExpirationDate: "EXPIRATION DATE",
    qualityWarningTitle: "Hindi Malinaw ang Larawan ng Lisensya",
    qualityWarningDesc: "Hindi namin mabasa nang maayos ang impormasyon mula sa nakuhang larawan. Pakisubukang kuhanan muli sa maliwanag na lugar nang walang silaw.",
    qualityRetakeBtn: "Kuhanan Muli",
    qualityManualEditBtn: "I-edit nang Mano-mano",
    analyzingImageQuality: "Sinusuri ang kalidad ng larawan...",
    tapToEnter: "Pindutin upang ilagay...",
  },
  en: {
    start: "Get Started",
    hasAccount: "Already have an account?",
    loginLink: "Login",
    selectRole: "How would you like to use SAKAY?",
    selectRoleDesc: "Choose an account type to get started. You can register as a passenger or driver.",
    passenger: "Passenger",
    passengerDesc: "Book tricycles around Calapan City",
    driver: "Driver",
    driverDesc: "Accept bookings and manage your trips",
    continue: "Continue",
    skip: "Skip",
    back: "Back",
    loginTitle: "Login",
    loginSubtitle: "Enter your mobile number and password to access your account.",
    phoneOrEmail: "Mobile Number",
    password: "Password",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    registerLink: "Create Account",
    createAccountTitle: "Create an account",
    prepareYourDetails: "Enter you details.",
    registerTitle: "Create an account",
    registerSubtitle: "Enter you details.",
    fullName: "Full Name",
    fullNamePlaceholder: "Full Name",
    mobileNumber: "Mobile Number",
    mobileNumberPlaceholder: "Mobile Number",
    mobilePhone: "Mobile Number (+63)",
    passwordPlaceholder: "Password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm Password",
    affiliatedToda: "Affiliated TODA",
    licenseNumber: "License Number",
    plateNumber: "Plate Number",
    franchiseNumberOptional: "Franchise / MTOP No. (Optional)",
    verificationDocs: "Documents for Verification",
    driversLicense: "Professional Driver's License",
    licenseUploaded: "Uploaded: drivers_license_front.jpg",
    tapToUpload: "Tap to upload photo",
    orCrMtop: "Tricycle OR / CR & MTOP Permit",
    orCrUploaded: "Uploaded: tricycle_or_cr_permit.pdf",
    photoWithTricycle: "Photo with Tricycle & Sidecar Body No.",
    photoUploaded: "Uploaded: driver_with_unit_photo.jpg",
    alreadyHaveAccount: "Already have an account?",
    enterPhoneAndPassword: "Please enter your mobile number and password.",
    sendOtpCode: "Send OTP Code",
    forgotPasswordTitle: "Forgot Password?",
    forgotPasswordDesc: "Enter your registered mobile number to receive a 6-digit verification code.",
    verifyOtpTitle: "Verify OTP",
    otpSentTo: "A 6-digit code was sent to",
    resendCode: "Resend Code",
    otpResentSuccess: "New OTP sent to your mobile number.",
    confirmOtp: "Confirm OTP",
    iAgree: "I Agree",
    termsTitle: "Terms of Service",
    privacyTitle: "Privacy Policy",
    lastUpdatedTerms: "Last updated: July 2026",
    didNotReceiveCode: "Didn't receive a code?",
    resend: "Resend",
    newPasswordTitle: "New Password",
    newPasswordDesc: "Create a new secure password for your driver account.",
    newPassword: "New Password",
    saveAndLogin: "Save & Login",
    applicationStatusTitle: "Application Status",
    submissionComplete: "1. Submission Complete",
    submissionCompleteDesc: "Driver's license and tricycle documents received.",
    todaRosterVerification: "2. TODA Driver Roster Verification",
    todaRosterVerificationDesc: "TODA Officers review unit allocation before endorsing to LGU.",
    lguAccreditation: "3. LGU Final Accreditation & Activation",
    lguAccreditationDesc: "Final approval and driver dispatch account activation.",
    goToDashboard: "Go to Driver Dashboard",
    createAccountBtn: "Continue",
    backToLogin: "Back to Login",
    phoneRequired: "Mobile number is required",
    passwordRequired: "Password is required",
    nameRequired: "Full name is required",
    passwordsMustMatch: "Passwords must match",
    successLogin: "Successfully logged in!",
    successRegister: "Successfully registered!",
    onboarding1Title: "Book a Ride",
    onboarding1Desc: "Fast and easy tricycle booking with just a tap, wherever you are.",
    onboarding2Title: "Fair & Transparent Fares",
    onboarding2Desc: "Clear, upfront pricing for every trip with no guesswork.",
    onboarding3Title: "Safe & Reliable",
    onboarding3Desc: "Guaranteed licensed drivers accredited by TODA will pick you up.",
    // Prepare Documents Screen
    prepareDocsTitle: "Prepare Documents",
    prepareDocsSubtitle: "To keep SAKAY safe for everyone, we need to verify your identity and vehicle documents. Please prepare these before proceeding.",
    prepareDocsBullet1: "Prepare the original documents.",
    prepareDocsBullet2: "Make sure all details are clear and legible.",
    prepareDocsBullet3: "Avoid blurry photos, glare, and shadows.",
    prepareDocsBullet4: "Take photos in a well-lit area.",
    docDriversLicenseTitle: "Driver's License (LTO)",
    docDriversLicenseDesc: "To verify your identity and driver's license.",
    docMtopTitle: "Motorized Tricycle Operator's Permit (MTOP)",
    docMtopDesc: "To verify your franchise and authorized route of operation.",
    docCrTitle: "Certificate of Registration (CR)",
    docCrDesc: "To verify your vehicle information.",
    docOrTitle: "Official Receipt (OR)",
    docOrDesc: "To verify the latest registration of your vehicle.",
    estimatedTimeNotice: "Estimated approximately 5 minutes",
    // Driver's License Guidelines Screen
    step1Of4: "Step 1 of 4",
    prepareLicenseTitle: "Prepare your Driver's License",
    forClearPhoto: "For a clear photo:",
    licenseBullet1: "Use only your official Driver's License card.",
    licenseBullet2: "Paper licenses are not accepted.",
    licenseBullet3: "Place the ID on a flat surface.",
    licenseBullet4: "Make sure the entire ID is visible.",
    licenseBullet5: "Avoid glare and shadows.",
    licenseBullet6: "Take photos in a well-lit area.",
    // License Scanner & Review 1-6 Screens
    scanFrontPromptPrefix: "Scan the ",
    scanBackPromptPrefix: "Scan the ",
    scanFrontWord: "front",
    scanBackWord: "back",
    scanPromptMid: " of your ",
    philippineDriversLicense: "Philippine Driver's License",
    scanPromptSuffix: " in the frame",
    tipsTitle: "Tips for taking a clear photo:",
    scanTipsHeader: "Tips for taking a clear photo:",
    useUploadInstead: "Upload photo instead",
    scanTip1: "Place your ID on a flat, well-lit surface.",
    scanTip2: "Make sure the entire ID fits within the frame.",
    scanTip3: "Tap the capture area to focus.",
    scanTip4: "Hold steady and press the camera button.",
    reviewPhotoTitle: "Does the photo look good?",
    reviewPhotoSubtitle: "Make sure all information on your ID is clear and readable.",
    useThisPhoto: "Use This Photo",
    retakePhoto: "Retake Photo",
    ocrProcessingNotice: "Please wait while we extract information from your document.",
    confirmInfoTitle: "Confirm you information",
    confirmInfoSubtitle: "Please verify that all details are correct.",
    useRearCameraError: "Use the rear camera to capture your driver's license.",
    labelFullName: "FULL NAME",
    labelDob: "DATE OF BIRTH",
    labelGender: "GENDER",
    genderMale: "Male",
    genderFemale: "Female",
    labelAddress: "ADDRESS",
    labelLicenseNumber: "DRIVER'S LICENSE NUMBER",
    labelDlCodes: "RESTRICTIONS",
    labelExpirationDate: "EXPIRATION DATE",
    qualityWarningTitle: "License Details Not Clear",
    qualityWarningDesc: "We could not clearly extract the details from the captured photo. Please try retaking the photo in a well-lit area without glare.",
    qualityRetakeBtn: "Retake Photo",
    qualityManualEditBtn: "Edit Manually",
    analyzingImageQuality: "Analyzing image quality...",
    tapToEnter: "Tap to enter...",
  }
};

interface LanguageContextType {
  language: Language;
  t: typeof translations['en'];
  setLanguage: (lang: Language) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('sakay_language');
    return (saved === 'tl' || saved === 'en') ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('sakay_language', lang);
  };

  const value = {
    language,
    t: translations[language],
    setLanguage,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
